version: '3.8'
services:
  db:
    build:
      context: ./db
    environment:
      POSTGRES_DB: uncorked
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data:
